/**
 * Somfy-specific io-homecontrol commands: 1W button frame (OPEN/CLOSE/STOP)
 * and the 1W pairing frame (cmd 0x30). Builds on iohc_frame.h/iohc_crypto.h.
 *
 * Source/verification: see iohc_constants.h — cross-validated between a
 * real sniffed Somfy frame (docs/radio.md), the command table
 * (docs/commands.md), and the hardware-validated implementation in
 * samr037/iohc-flipper.
 */
#pragma once
#include <stdint.h>
#include <stddef.h>

namespace iohc {

constexpr size_t MAX_TX_FRAME_SIZE = 40;

/**
 * Builds a complete, authenticated 1W button frame (cmd 0x00: Activate/
 * Execute Function) for OPEN/CLOSE/STOP, ready to transmit.
 *
 * src:         our own 3-byte NodeID
 * dest:        target address (BROADCAST_ADDR for a normal transmission)
 * button_code: BTN_OPEN / BTN_CLOSE / BTN_STOP
 * seq:         current sequence number (must be incremented after every
 *              transmission and persisted, see the NVS requirement in phase 3)
 * install_key: the 128-bit key shared during pairing
 * out/out_size: output buffer; returns the number of bytes written, or 0 on error.
 */
size_t build_button_frame(const uint8_t src[3], const uint8_t dest[3],
                           uint8_t button_code, uint16_t seq,
                           const uint8_t install_key[16],
                           uint8_t* out, size_t out_size,
                           bool low_power_mode = false);

/**
 * Builds the 1W pairing frame (cmd 0x30: Send 1W Key). NO MAC (confirmed:
 * the actuator does not know our key yet, so it cannot verify a MAC with
 * it either — only the key itself is protected, via the transfer-key XOR).
 *
 * src:         our own (newly chosen) 3-byte NodeID
 * dest:        BROADCAST_ADDR (Somfy actuators listen on this while in PROG mode)
 * install_key: the NEW 128-bit key we want to hand to the actuator
 *              (randomly generated by us, keep it — this becomes your stack key)
 * seq:         sequence number for this pairing frame
 */
size_t build_pairing_frame(const uint8_t src[3], const uint8_t dest[3],
                            const uint8_t install_key[16], uint16_t seq,
                            uint8_t* out, size_t out_size,
                            bool low_power_mode = false);

/**
 * Builds the 1W "remove controller" announce frame (cmd 0x39), which
 * according to docs/linklayer.md and iohc-flipper is sent before the
 * pairing frame. The field layout matches an authenticated frame, but
 * without our key known to the actuator the MAC is meaningless here —
 * iohc-flipper fills it in anyway with install_key (our just-chosen key);
 * we do the same for consistency.
 */
size_t build_remove_controller_frame(const uint8_t src[3], const uint8_t dest[3],
                                      uint16_t seq, const uint8_t install_key[16],
                                      uint8_t* out, size_t out_size,
                                      bool low_power_mode = false);

} // namespace iohc
